version: '2'

services: 
  app:
    container_name: ms-helloworld
    build: .
    volumes:
      - .:/go/src/github.com/inadarei/justgo
      - /go/src/github.com/inadarei/justgo/vendor
    ports:
      - 3000
    environment:
      - APP_ENV=development
    command: ["gin", "run"]

# @see: https://github.com/codegangsta/gin

